// Icon aliases in one place, so swapping the icon set touches one file.
// Phosphor, matching the Icons page of the Woolgaze Figma design system.
export {
  IconContext,
  BooksIcon as Books,
  GridFourIcon as GridFour,
  YarnIcon as Yarn,
  BookOpenIcon as BookOpen,
  GearIcon as Gear,
  PlusIcon as Plus,
  MinusIcon as Minus,
  CameraIcon as Camera,
  LinkIcon,
  FileTextIcon as FileText,
  ArrowLeftIcon as ArrowLeft,
  TrashIcon as Trash,
  ShareNetworkIcon as ShareNetwork,
  CopyIcon as Copy,
  PencilSimpleIcon as PencilSimple,
  CheckIcon as Check,
  CaretUpIcon as CaretUp,
  CaretDownIcon as CaretDown,
  CaretLeftIcon as CaretLeft,
  MagnifyingGlassIcon as MagnifyingGlass,
  ArrowSquareOutIcon as ArrowSquareOut,
  FunnelIcon as Filter,
  FunnelXIcon as FilterX,
  RepeatIcon as Repeat,
  FolderIcon as Folder,
  FolderPlusIcon as FolderPlus,
  FolderOpenIcon as FolderOpen,
  DotsThreeIcon as DotsThree,
  ArrowSquareInIcon as ArrowSquareIn,
  XIcon as X,
  ArrowCounterClockwiseIcon as ArrowCounterClockwise,
  ArrowUUpLeftIcon as ArrowUUpLeft,
  MapPinIcon as MapPin,
  UploadSimpleIcon as UploadSimple,
} from '@phosphor-icons/react';
